version: "3.9"

services:
  web:
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    command: >
      bash -c
        "python3 manage.py migrate
        python3 manage.py runserver 0.0.0.0:8000"
    restart: always
    depends_on:
      - db
    environment:
      POSTGRES_HOST: db
  db:
    image: postgres:latest
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=payments_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    restart: always
